### ISSUE TITLE
@conda-forge-admin, please add user @schlunma

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/esmvaltool-suite-feedstock#1]
Adding upstream release manager for 2.5.x releases.

**Comment by valeriupredoi** [comment]
@zklaus any clue why smithy doesn't get activated?

**Comment by zklaus** [comment]
Probably the same problem as in esmvalcore-feedstock: A broken list of maintainers to start with.

**Comment by zklaus** [comment]
Ah no, in this case: Why are you opening issues in your fork?

**Comment by valeriupredoi** [comment]
:man_facepalming: x 10 :rofl:

**Comment by valeriupredoi** [comment]
thnaks dude, what an absolute doofus :laughing: The issue in the correct repo triggered the CI instantly :grin:
